/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/details` | `/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/edit` | `/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/details` | `/[id]/details`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/edit` | `/[id]/edit`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(tickets)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(tickets)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(tickets)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}${'/(tickets)'}/${Router.SingleRoutePart<T>}/details` | `/${Router.SingleRoutePart<T>}/details` | `${'/(tabs)'}${'/(tickets)'}/${Router.SingleRoutePart<T>}/edit` | `/${Router.SingleRoutePart<T>}/edit` | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/details` | `/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}${'/(tickets)'}/[id]/edit` | `/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
